name: resume
channels:
- !!python/unicode
  'defaults'
dependencies:
- !!python/unicode
  'openssl=1.0.2h=2'
- !!python/unicode
  'pip=8.1.2=py27_0'
- !!python/unicode
  'python=2.7.12=1'
- !!python/unicode
  'readline=6.2=2'
- !!python/unicode
  'setuptools=26.1.1=py27_0'
- !!python/unicode
  'sqlite=3.13.0=0'
- !!python/unicode
  'tk=8.5.18=0'
- !!python/unicode
  'wheel=0.29.0=py27_0'
- !!python/unicode
  'zlib=1.2.8=3'
- pip:
  - argcomplete==1.8.2
  - beautifulsoup4==4.5.3
  - chardet==2.3.0
  - docx2txt==0.6
  - ebooklib==0.15
  - lxml==4.1.0
  - numpy==1.13.3
  - olefile==0.44
  - pandas==0.20.3
  - pillow==4.3.0
  - pocketsphinx==0.1.3
  - python-dateutil==2.6.1
  - python-pptx==0.6.5
  - pytz==2017.2
  - six==1.10.0
  - speechrecognition==3.6.3
  - textract==1.6.1
  - xlrd==1.0.0
  - xlsxwriter==1.0.2
